In [1]:
#1. Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів натуральних чисел, починаючи з 2, та виведіть його значення.
import math

# Створити список чисел від 2 до 10 (включно)
number = list(range(2, 11))

# Обчислити факторіал для кожного числа
factorial = [math.factorial(n) for n in number]

# Обчислити обернене значення для кожного факторіала
inverse_factorial = [1/f for f in factorial]

# Вивести список обернених значень факторіалів
print(inverse_factorial)

[0.5, 0.16666666666666666, 0.041666666666666664, 0.008333333333333333, 0.001388888888888889, 0.0001984126984126984, 2.48015873015873e-05, 2.7557319223985893e-06, 2.755731922398589e-07]


In [2]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненимизначеннями синусів кожного натурального числа, починаючи з 1, та виведіть йогозначення.
import numpy as np

# Створити список чисел від 1 до 9 (включно) для заповнення матриці 3x3
numbers = list(range(1, 10))

# Обчислити синус для кожного числа та взяти обернене значення
inverse_sines = [1 / np.sin(n) for n in numbers]

# Перетворити список в матрицю 3x3
matrix = np.array(inverse_sines).reshape(3, 3)

# Вивести матрицю
print("Матриця обернених значень синусів:\n", matrix)


Матриця обернених значень синусів:
 [[ 1.18839511  1.09975017  7.0861674 ]
 [-1.32134871 -1.04283521 -3.57889955]
 [ 1.52210106  1.01075622  2.42648664]]


In [3]:
#Створіть масив розміром 4x4, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть суму елементів кожного рядка.
import numpy as np

# Створити масив 4x4 з випадковими натуральними числами від 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

matrix_sum = np.sum(matrix, axis=1)

print("Згенерована матриця:\n", matrix)
print("\nСуми елементів кожного рядка:", matrix_sum)

Згенерована матриця:
 [[31 27 15 46]
 [27 32 42  5]
 [47 47 48 48]
 [ 6 25 45 44]]

Суми елементів кожного рядка: [119 106 190 120]


In [4]:
#Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від -1.5 до 1.5 та виведіть його значення.
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від -1.5 до 1.5
matrix = np.random.uniform(-1.5, 1.5, size=(3, 3))

print("Згенерована матриця:\n", matrix)

Згенерована матриця:
 [[-1.45265969 -0.38493743 -0.72916308]
 [-0.93256452  1.03651637  0.85360134]
 [-0.22782706 -0.62359509  0.3324656 ]]


In [5]:
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні
#від 8 до 12 та виконайте на них поелементні операції додавання, віднімання та множення.#
import numpy as np

# Створити два одновимірних масиви розміром 4 з випадковими цілими числами від 8 до 12
array1 = np.random.randint(8, 13, size=4)
array2 = np.random.randint(8, 13, size=4)

# Виконати поелементні операції
add_res = array1 + array2
sub_res = array1 - array2
multi_res = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("\nДодавання:", add_res)
print("Віднімання:", sub_res)
print("Множення:", multi_res)

Масив 1: [11 10 11 12]
Масив 2: [ 9 10 10 12]

Додавання: [20 20 21 24]
Віднімання: [2 0 1 0]
Множення: [ 99 100 110 144]


In [6]:
#Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 15 та знайдіть їх добуток.
import numpy as np

# Створити дві матриці 4x4 з випадковими цілими числами від 1 до 15
matrix1 = np.random.randint(1, 16, size=(4, 4))
matrix2 = np.random.randint(1, 16, size=(4, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nДобуток матриць:\n", product)

Матриця 1:
 [[15  9 11 13]
 [ 4  8 10  3]
 [ 3  5  7  8]
 [13  6  7 13]]

Матриця 2:
 [[ 9  3  2 15]
 [ 1  2  8 14]
 [15  8 15  2]
 [ 5  7  6  9]]

Добуток матриць:
 [[374 242 345 490]
 [209 129 240 219]
 [177 131 199 201]
 [293 198 257 410]]


In [7]:
#Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.
import numpy as np

# Створити матрицю 4x2 з випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, size=(4, 2))

# Створити матрицю 2x2 з випадковими цілими числами від 1 до 3
matrix2 = np.random.randint(1, 4, size=(2, 2))

# Перемножити матриці
result = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРезультат перемноження матриць:\n", result)

Матриця 1:
 [[1 1]
 [2 2]
 [2 2]
 [2 1]]

Матриця 2:
 [[2 2]
 [2 2]]

Результат перемноження матриць:
 [[4 4]
 [8 8]
 [8 8]
 [6 6]]


In [8]:
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np

# Створити матрицю 2x2 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 2))

# Знайти обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

print("Оригінальна матриця:\n", matrix)
print("\nОбернена матриця:\n", inverse_matrix)

Оригінальна матриця:
 [[5 1]
 [7 5]]

Обернена матриця:
 [[ 0.27777778 -0.05555556]
 [-0.38888889  0.27777778]]


In [9]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -4 до 10 та транспонуйте її.
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від -4 до 10
matrix = np.random.uniform(-4, 10, size=(3, 3))

# Транспонувати матрицю
transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця:\n", matrix)
print("\nТранспонована матриця:\n", transposed_matrix)

Оригінальна матриця:
 [[-3.45454056  5.75454156 -2.41992416]
 [ 4.78546328  1.88854161 -3.54269453]
 [-0.1959395  -3.00013277 -1.81442854]]

Транспонована матриця:
 [[-3.45454056  4.78546328 -0.1959395 ]
 [ 5.75454156  1.88854161 -3.00013277]
 [-2.41992416 -3.54269453 -1.81442854]]


In [10]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими
# дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

# Створити матрицю 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створити вектор 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

# Знайти добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[0.45800991 0.22653807 0.07465263 0.3839202 ]
 [0.664045   0.73458143 0.18332281 0.40376457]
 [0.48734573 0.42194834 0.03667    0.63871456]]

Вектор:
 [[0.47200711]
 [0.43325265]
 [0.73843514]
 [0.790462  ]]

Результат множення матриці на вектор:
 [[0.67293261]
 [1.08622587]
 [0.94479889]]


In [11]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими
# цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[0.55246672 0.41759995 0.64685594]
 [0.01673611 0.58550519 0.20383894]]

Вектор:
 [[10]
 [ 2]
 [10]]

Результат множення матриці на вектор:
 [[12.82842659]
 [ 3.37676091]]


In [12]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть відношення всіх
#елементів першої матриці до відповідних елементів другої матриці (поелементне ділення).
import numpy as np

# Створити дві матриці 3x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

# Знайти відношення всіх елементів першої матриці до відповідних елементів другої матриці
result = matrix1 / matrix2

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРезультат поелементного ділення:\n", result)

Матриця 1:
 [[4 2 1]
 [1 1 1]
 [4 3 2]]

Матриця 2:
 [[3 2 2]
 [5 5 3]
 [3 4 1]]

Результат поелементного ділення:
 [[1.33333333 1.         0.5       ]
 [0.2        0.2        0.33333333]
 [1.33333333 0.75       2.        ]]


In [13]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.
import numpy as np

# Створити дві матриці 4x4 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(4, 4)
matrix2 = np.random.rand(4, 4)

# Знайти різницю елементів матриць
difference = matrix1 - matrix2

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРізниця матриць:\n", difference)

Матриця 1:
 [[0.16628156 0.57375035 0.69589713 0.23167843]
 [0.40342042 0.71591652 0.78378421 0.6301199 ]
 [0.74966446 0.08991618 0.42244318 0.54825803]
 [0.43678205 0.134335   0.77729487 0.74384073]]

Матриця 2:
 [[0.54771364 0.44533693 0.2149977  0.84388716]
 [0.52648151 0.47756568 0.26145839 0.16420615]
 [0.85469618 0.41725841 0.90914448 0.86091547]
 [0.04500825 0.18779062 0.86301388 0.52947956]]

Різниця матриць:
 [[-0.38143208  0.12841343  0.48089942 -0.61220873]
 [-0.12306109  0.23835084  0.52232583  0.46591375]
 [-0.10503172 -0.32734222 -0.48670131 -0.31265744]
 [ 0.3917738  -0.05345562 -0.08571901  0.21436117]]


In [14]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі.
import numpy as np

# Створити матрицю 4x4 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(4, 4))

# Знайти суму елементів на побічній діагоналі
secondary_diagonal_sum = np.trace(np.fliplr(matrix))

print("Згенерована матриця:\n", matrix)
print("\nСума елементів на побічній діагоналі:", secondary_diagonal_sum)

Згенерована матриця:
 [[ 6.15575874  3.35960908 -0.67355439  2.2030606 ]
 [-6.21205999  1.80458209  9.45746983 -9.97399675]
 [ 6.48365064 -8.60832049 -6.11911502 -2.2357615 ]
 [ 3.67639662 -8.26267443 -8.38456009 -6.71320023]]

Сума елементів на побічній діагоналі: 6.728606546562196


In [15]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть
#вектор-стовпчик, що містить суму квадратів елементів кожного стовпця матриці
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Обчислити суму квадратів елементів кожного стовпця
column_sums_of_squares = np.sum(matrix ** 2, axis=0)

# Перетворити результат на вектор-стовпчик
column_sums_of_squares = column_sums_of_squares.reshape(-1, 1)

print("Матриця:\n", matrix)
print("\nВектор-стовпчик суми квадратів елементів кожного стовпця:\n", column_sums_of_squares)

Матриця:
 [[0.23329701 0.65411795 0.71055149]
 [0.86718665 0.53690252 0.49598101]
 [0.01794395 0.13136969 0.35397551]]

Вектор-стовпчик суми квадратів елементів кожного стовпця:
 [[0.80676217]
 [0.73339261]
 [0.87617925]]


In [16]:
#Ми створювали матриці та вектори, заповнювали їх випадковими числами, а потім виконували такі дії, як множення, додавання, віднімання і так далі.
#Ми також обчислювали суми елементів, добутки та середні значення.